import React from 'react';
import { SessionProvider } from 'next-auth/react';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  if (typeof window !== 'undefined') {
    // Render the SessionProvider only on the client-side
    return (
      <html lang="en">
        <body className={inter.className}>
          <SessionProvider session={null}>
            {children}
          </SessionProvider>
        </body>
      </html>
    );
  }

  // For server-side rendering, render the children directly
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}